ureca:
  secret-key: ${URECA_SECRET_KEY}
  hash-key: ${URECA_HASH_KEY}
billing:
  grafana:
    iframe-url: https://grafana.4e-um.cloud/public-dashboards/1656cac08ded4a22820d1ec97d3edad6?orgId=1
    refresh-interval: 5s
