project:
  name: API Core
  version: 1.0.0

spring:
  profiles:
    include: secret

  application:
    name: api-core

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:app_db}
    username: ${POSTGRES_USER:app_user}
    password: ${POSTGRES_PASSWORD:app_password}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
      validation-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중이면 update, 초기 테스트면 create-drop 등으로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    open-in-view: false


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${OTEL_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

billing:
  grafana:
    iframe-url: https://grafana.example.com/d/xxx
    refresh-interval: 5s