ureca:
  secret-key: ${URECA_SECRET_KEY}
  hash-key: ${URECA_HASH_KEY}
billing:
  grafana:
    iframe-url: http://34.22.76.102/d-solo/cfb0vm63z241sc/test?orgId=1&from=1769139882304&to=1769161482304&timezone=browser&panelId=1&__feature.dashboardSceneSolo
    refresh-interval: 5s
