ureca:
  secret-key: ${URECA_SECRET_KEY}
  hash-key: ${URECA_HASH_KEY}
billing:
  grafana:
    iframe-url: ${BILLING_GRAFANA_IFRAME_URL}
    refresh-interval: ${BILLING_GRAFANA_REFRESH_INTERVAL:5s}
cloud:
  function:
    base-url: ${CLOUD_FUNCTION_BASE_URL}
